<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Inventory Report - {{ $business->name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 11px;
            color: #1a1a1a;
            background: #fff;
            padding: 30px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 20px;
            margin-bottom: 5px;
            color: #111827;
        }
        .header p {
            color: #4b5563;
            font-size: 12px;
        }
        .report-info {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .report-info-col {
            display: table-cell;
            width: 50%;
        }
        .report-info-right {
            text-align: right;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
            font-weight: bold;
            color: #374151;
            text-transform: uppercase;
            font-size: 10px;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .low-stock {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #6b7280;
            border-top: 1px solid #e5e7eb;
            padding-top: 10px;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>{{ $business->name }}</h1>
        <p>{{ $business->address }} {{ $business->state }} {{ $business->pincode }}</p>
        @if($business->phone) <p>Phone: {{ $business->phone }}</p> @endif
    </div>

    <div class="report-info">
        <div class="report-info-col">
            <h2 style="font-size: 16px; margin: 0; color: #111827;">Inventory Report</h2>
        </div>
        <div class="report-info-col report-info-right">
            <p><strong>Date:</strong> {{ date('d M Y, h:i A') }}</p>
            <p><strong>Total Items:</strong> {{ $products->count() }}</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 5%">#</th>
                <th style="width: 25%">Product Name</th>
                <th style="width: 15%">Brand</th>
                <th style="width: 15%">Category</th>
                <th style="width: 10%" class="text-right">Stock</th>
                <th style="width: 15%" class="text-right">Purchase Price</th>
                <th style="width: 15%" class="text-right">MRP</th>
            </tr>
        </thead>
        <tbody>
            @forelse($products as $index => $product)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>
                        <strong>{{ $product->model_name }}</strong>
                    </td>
                    <td>{{ $product->brand ? $product->brand->name : '-' }}</td>
                    <td>{{ $product->category ? $product->category->name : '-' }}</td>
                    <td class="text-right {{ $product->quantity <= 5 ? 'low-stock' : '' }}">
                        {{ $product->quantity }}
                    </td>
                    <td class="text-right">₹{{ number_format($product->purchase_price, 2) }}</td>
                    <td class="text-right">₹{{ number_format($product->mrp, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" class="text-center">No products found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by Billing System &bull; {{ date('Y') }}
    </div>

</body>
</html>
