<?php

namespace App\Http\Controllers\Api\Superadmin;

use App\Http\Controllers\BaseController;
use App\Models\Commission;
use App\Services\CommissionService;
use Illuminate\Http\Request;
use OpenApi\Attributes as OA;

class CommissionController extends BaseController
{
    protected $commissionService;

    /**
     * Inject the CommissionService dependency.
     */
    public function __construct(CommissionService $commissionService)
    {
        $this->commissionService = $commissionService;
    }

    #[OA\Get(
        path: '/superadmin/commissions',
        summary: 'List Commissions',
        description: 'Get a list of all commissions generated by partners.',
        tags: ['Superadmin - Commissions'],
        security: [['sanctum' => []]],
        responses: [
            new OA\Response(response: 200, description: 'Successful operation')
        ]
    )]
    public function index(Request $request)
    {
        // Support either returning all data (backward compatibility) or paginated data
        if ($request->input('all') === 'true' || $request->input('per_page') == -1) {
            $commissions = Commission::with(['partner', 'business', 'plan'])->get();
            return $this->success($commissions, 'Commissions retrieved successfully');
        }

        $filters = $request->only(['status', 'partner_id', 'search', 'sort_by', 'sort_order', 'from_date', 'to_date']);
        $perPage = $request->input('per_page', 10);

        $paginator = $this->commissionService->getPaginatedCommissions($filters, $perPage);
        return $this->paginated($paginator, 'Commissions retrieved successfully');
    }

    #[OA\Get(
        path: '/superadmin/commissions/{id}',
        summary: 'Get Commission Details',
        description: 'Retrieves a single commission with its associated partner, business, and plan details.',
        tags: ['Superadmin - Commissions'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))
        ],
        responses: [
            new OA\Response(response: 200, description: 'Successful operation'),
            new OA\Response(response: 404, description: 'Commission not found')
        ]
    )]
    public function show($id)
    {
        try {
            $commission = $this->commissionService->getCommissionDetails((int) $id);
            return $this->success($commission, 'Commission retrieved successfully');
        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return $this->notFound('Commission not found.');
        }
    }

    #[OA\Patch(
        path: '/superadmin/commissions/{id}/mark-paid',
        summary: 'Mark Commission as Paid',
        description: 'Updates a pending commission to paid status.',
        tags: ['Superadmin - Commissions'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(name: 'id', in: 'path', required: true, schema: new OA\Schema(type: 'integer'))
        ],
        responses: [
            new OA\Response(response: 200, description: 'Commission marked as paid'),
            new OA\Response(response: 400, description: 'Commission is already paid')
        ]
    )]
    public function markAsPaid(Request $request, $id)
    {
        try {
            $commission = $this->commissionService->markCommissionAsPaid((int) $id);
            return $this->success($commission, 'Commission marked as paid');
        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return $this->notFound('Commission not found.');
        } catch (\Exception $e) {
            return $this->error($e->getMessage(), 400);
        }
    }
}
